export const TEAMMEMBERS = [
    {
        key: 1,
        name: "Michael M.",
        role: "Software/Mechanical Engineer",
        github: "KollihTheGuruh",
        weblink: "#",
        email: "mmike8449@gmail.com",
        whatsapp: "+254717219123",
        twitter: "MikeTheGuruh",
        linkedin: "michael-mutinda-177619266",
    },
    {
        key: 2,
        name: "Merlix G.",
        role: "Full-stack Engineer",
        github: "mergik",
        weblink: "https://www.mergik.tech/",
        email: "contact@mgm.anonaddy.me",
        whatsapp: "#",
        twitter: "mergiktech",
        linkedin: "#",
    },
    {
        key: 3,
        name: "Annah N.",
        role: "Software Engineer/SEO Marketer",
        github: "njugunaannah",
        weblink: "#",
        email: "njugunaannah@gmail.com",
        whatsapp: "#",
        twitter: "NjugunaAnnah",
        linkedin: "annah-njuguna",
    },
    {
        key: 4,
        name: "Hillary K.",
        role: "Full-stack Engineer",
        github: "hillary-254",
        weblink: "#",
        email: "hillarykiprotich35@gmail.com",
        whatsapp: "#",
        twitter: "larykips5",
        linkedin: "hillary-kiprotich254",
    },
    {
        key: 5,
        name: "Kennedy R.",
        role: "Full-stack Engineer/Project Manager",
        github: "KennedyRyan-code",
        weblink: "https://cosmictech.com",
        email: "kenryan49@gmail.com",
        whatsapp: "#",
        twitter: "ken_pachyy",
        linkedin: "kennedy-kim",
    },
    {
        key: 6,
        name: "Steve M.",
        role: "Cloud Architect",
        github: "Stevecmd",
        weblink: "#",
        email: "#",
        whatsapp: "#",
        twitter: "stevedevex",
        linkedin: "steve-murimi",
    },
];