export const TEAMMEMBERS = [
    {
        key: 1,
        name: "Michael M.",
        role: "#",
        github: "KollihTheGuruh",
        weblink: "#",
        email: "#",
        whatsapp: "+254717219123",
        twitter: "#",
        linkedin: "#",
    },
    {
        key: 2,
        name: "Merlix G.",
        role: "Full-stack Developer",
        github: "mergik",
        weblink: "https://www.mergik.tech/",
        email: "contact@mgm.anonaddy.me",
        whatsapp: "#",
        twitter: "mergiktech",
        linkedin: "#",
    },
    {
        key: 3,
        name: "Annah N.",
        role: "#",
        github: "njugunaannah",
        weblink: "#",
        email: "#",
        whatsapp: "#",
        twitter: "#",
        linkedin: "#",
    },
    {
        key: 4,
        name: "Hillary K.",
        role: "Full-stack Developer",
        github: "hillary-254",
        weblink: "#",
        email: "#",
        whatsapp: "#",
        twitter: "#",
        linkedin: "#",
    },
    {
        key: 5,
        name: "Kennedy R.",
        role: "#",
        github: "KennedyRyan-code",
        weblink: "#",
        email: "#",
        whatsapp: "#",
        twitter: "#",
        linkedin: "#",
    },
    {
        key: 6,
        name: "Steve M.",
        role: "#",
        github: "Stevecmd",
        weblink: "#",
        email: "#",
        whatsapp: "#",
        twitter: "#",
        linkedin: "#",
    },
];